### ISSUE TITLE
pin python version in the env.yml

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#182]
Today, recreated environment and it installed Python 3.12.  Could not pip install gemviz later.

<details>

Cluster of errors:

```bash
 (gemviz) [onyxia ~/src/gemviz] conda env create --force -n gemviz -f ./env.yml
Channels:
 - conda-forge
 - defaults
 - apsu
 - aps-anl-tag
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/RODOLAKIS/.conda/envs/gemviz/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting tiled>=0.1.0a104 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached tiled-0.1.0a109-py3-none-any.whl.metadata (16 kB)
Collecting build (from -r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 2))
  Downloading build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting setuptools-scm (from -r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 3))
  Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=19.0 in /home/RODOLAKIS/.conda/envs/gemviz/lib/python3.12/site-packages (from build->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 2)) (23.2)
Collecting pyproject_hooks (from build->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 2))
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: setuptools in /home/RODOLAKIS/.conda/envs/gemviz/lib/python3.12/site-packages (from setuptools-scm->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 3)) (68.2.2)
Collecting typing-extensions (from setuptools-scm->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 3))
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting aiofiles (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Collecting aiosqlite (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached aiosqlite-0.19.0-py3-none-any.whl (15 kB)
Collecting alembic (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached alembic-1.12.1-py3-none-any.whl.metadata (7.3 kB)
Collecting anyio (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached anyio-4.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting appdirs (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting asyncpg (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached asyncpg-0.29.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Collecting awkward>=2.4.3 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached awkward-2.4.9-py3-none-any.whl.metadata (6.9 kB)
Collecting blosc (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached blosc-1.11.1.tar.gz (1.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting cachetools (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached cachetools-5.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting cachey (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached cachey-0.2.1-py3-none-any.whl (6.4 kB)
Collecting click!=8.1.0 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting dask (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached dask-2023.10.1-py3-none-any.whl.metadata (3.7 kB)
Collecting entrypoints (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting fastapi (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached fastapi-0.104.1-py3-none-any.whl.metadata (24 kB)
Collecting h5netcdf (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached h5netcdf-1.2.0-py3-none-any.whl.metadata (13 kB)
Collecting h5py (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached h5py-3.10.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting httpx!=0.23.1,>=0.20.0 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached httpx-0.25.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jinja2 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jmespath (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting jsonschema (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached jsonschema-4.19.2-py3-none-any.whl.metadata (7.9 kB)
Collecting lz4 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached lz4-4.3.2.tar.gz (170 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting msgpack>=1.0.0 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached msgpack-1.0.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting ndindex (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached ndindex-1.7-py3-none-any.whl (85 kB)
Requirement already satisfied: numpy in /home/RODOLAKIS/.conda/envs/gemviz/lib/python3.12/site-packages (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1)) (1.26.0)
Collecting openpyxl (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting orjson (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached orjson-3.9.10-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (49 kB)
Collecting pandas (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached pandas-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting parquet (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached parquet-1.3.1-py3-none-any.whl (24 kB)
Collecting pillow (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached Pillow-10.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting prometheus-client (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached prometheus_client-0.18.0-py3-none-any.whl.metadata (26 kB)
Collecting psutil (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached psutil-5.9.6-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting pyarrow (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached pyarrow-14.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting pydantic<2,>=1.8.2 (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached pydantic-1.10.13-py3-none-any.whl.metadata (149 kB)
Collecting python-dateutil (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-jose[cryptography] (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
Collecting python-multipart (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)
Collecting pyyaml (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting sparse (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached sparse-0.14.0-py2.py3-none-any.whl (80 kB)
Collecting sqlalchemy>=2 (from sqlalchemy[asyncio]>=2; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached SQLAlchemy-2.0.23-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting starlette (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached starlette-0.32.0.post1-py3-none-any.whl.metadata (5.8 kB)
Collecting tifffile (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached tifffile-2023.9.26-py3-none-any.whl.metadata (30 kB)
Collecting toolz (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting typer (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting uvicorn[standard] (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached uvicorn-0.24.0.post1-py3-none-any.whl.metadata (6.4 kB)
Collecting watchgod (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached watchgod-0.8.2-py3-none-any.whl (12 kB)
Collecting xarray (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached xarray-2023.10.1-py3-none-any.whl.metadata (10 kB)
Collecting zarr (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached zarr-2.16.1-py3-none-any.whl.metadata (5.8 kB)
Collecting zstandard (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached zstandard-0.22.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
Collecting awkward-cpp==25 (from awkward>=2.4.3->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached awkward_cpp-25-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting certifi (from httpx!=0.23.1,>=0.20.0->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore (from httpx!=0.23.1,>=0.20.0->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached httpcore-1.0.1-py3-none-any.whl.metadata (20 kB)
Collecting idna (from httpx!=0.23.1,>=0.20.0->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting sniffio (from httpx!=0.23.1,>=0.20.0->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy>=2->sqlalchemy[asyncio]>=2; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached greenlet-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting Mako (from alembic->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)
Collecting heapdict (from cachey->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Collecting cloudpickle>=1.5.0 (from dask->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting fsspec>=2021.09.0 (from dask->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Collecting partd>=1.2.0 (from dask->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached partd-1.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting importlib-metadata>=4.13.0 (from dask->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Collecting pytz>=2020.1 (from pandas->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting six>=1.5 (from python-dateutil->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting anyio (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting starlette (from tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
Collecting MarkupSafe>=2.0 (from jinja2->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached MarkupSafe-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
Collecting attrs>=22.2.0 (from jsonschema->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached jsonschema_specifications-2023.7.1-py3-none-any.whl.metadata (2.8 kB)
Collecting referencing>=0.28.4 (from jsonschema->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached referencing-0.30.2-py3-none-any.whl.metadata (2.6 kB)
Collecting rpds-py>=0.7.1 (from jsonschema->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached rpds_py-0.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting et-xmlfile (from openpyxl->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Collecting thriftpy2 (from parquet->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached thriftpy2-0.4.17.tar.gz (519 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting ecdsa!=0.15 (from python-jose[cryptography]; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached ecdsa-0.18.0-py2.py3-none-any.whl (142 kB)
Collecting rsa (from python-jose[cryptography]; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1 (from python-jose[cryptography]; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting cryptography>=3.4.0 (from python-jose[cryptography]; extra == "all"->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached cryptography-41.0.5-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Collecting scipy>=0.19 (from sparse->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached scipy-1.11.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting numba>=0.49 (from sparse->tiled[all]>=0.1.0a104->-r /home/RODOLAKIS/src/gemviz/condaenv.senpbjr8.requirements.txt (line 1))
  Using cached numba-0.58.1.tar.gz (2.6 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xuoxy0ja/numba_b50d07b9289d447ebb410b9cd71d6c7a/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-xuoxy0ja/numba_b50d07b9289d447ebb410b9cd71d6c7a/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

</details>

Thanks, @rodolakis, for reporting.

**Comment by rodolakis** [comment]
I edited the issue to include the error in its entirety (in case it helps?)

**Comment by rodolakis** [comment]
Worked with the following:

```yml
name: gemviz

# conda env create --force -n gemviz -f ./env.yml --solver=libmamba

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.7, <3.12
  - pip
  - pyqt =5
  - pyqtgraph
  - pyRestTable
  - qt =5

  - pip:
    - tiled[all] >=0.1.0a104

  # needed by developer
    - build
    - setuptools-scm
  ```

**Comment by prjemian** [comment]
I believe it should start with >=3.8: https://github.com/BCDA-APS/gemviz/blob/88fc4b114a2aedf9a18d0983ab8d53b6f96f425c/.github/workflows/unit_tests.yml#L52-L57

**Comment by prjemian** [comment]
By the way, recently, I learned I must revise this part of the packaging: https://github.com/BCDA-APS/gemviz/blob/88fc4b114a2aedf9a18d0983ab8d53b6f96f425c/pyproject.toml#L1-L9

The `[build-system]` part is for packages needed to build a source distribution or wheel.  There is another section for required or optional parts.

**Comment by prjemian** [comment]
This [conversation](https://github.com/bluesky/hklpy/pull/276#discussion_r1366078631) describes what was needed to convert the hklpy packaging.
