### ISSUE TITLE
BUG: plotting while run is still open

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#185]
Tried plotting from a run while it was still open (data was still being collected).  Here's the exception trace:

```py
(base) jemian@otz ~ $ conda activate gemviz
(gemviz) jemian@otz ~ $ gemviz &
[1] 149795
(gemviz) jemian@otz ~ $ Traceback (most recent call last):
  File "/home/beams1/JEMIAN/Documents/projects/BCDA-APS/gemviz/gemviz/bluesky_runs_catalog.py", line 121, in doRunSelectedSlot
    self.brc_run_viz.setData(tapi.run_description_table(run))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams1/JEMIAN/Documents/projects/BCDA-APS/gemviz/gemviz/tapi.py", line 234, in run_description_table
    data = stream["data"].read()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/JEMIAN/.conda/envs/gemviz/lib/python3.11/site-packages/tiled/client/xarray.py", line 101, in read
    return xarray.Dataset(
           ^^^^^^^^^^^^^^^
  File "/home/beams/JEMIAN/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/dataset.py", line 685, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/JEMIAN/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/dataset.py", line 416, in merge_data_and_coords
    return merge_core(
           ^^^^^^^^^^^
  File "/home/beams/JEMIAN/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/merge.py", line 723, in merge_core
    dims = calculate_dimensions(variables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/JEMIAN/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/variable.py", line 3257, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'time': length 24 on 'time' and length 22 on {'time': 'timebase'}
gemviz &
[2] 149974
[1]   Aborted                 (core dumped) gemviz
```

**Comment by prjemian** [comment]
```py
(gemviz) jemian@otz ~ $ gemviz --version
0.0.2.dev203+g9b20622
```

**Comment by prjemian** [comment]
Also, when a run is open, its entry in the table model does not change as collection continues.  That's a bug related to _plotting while run is open_.

**Comment by prjemian** [comment]
Likely that #185, #207, & #208 are related.
