### ISSUE TITLE
BUG: ImportError at XPCS crashes the app - due to xarray version 2023.12.0

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#220]
Updated main branch from GitHub at XPCS today.  Catalog opens but clocking on any of the runs first shown crashes the app:

```py
(gemviz) 8idiuser@amber ~/tiled-server $ Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/gemviz/bluesky_runs_catalog.py", line 130, in doRunSelectedSlot
    from .select_stream_fields import SelectFieldsWidget
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/gemviz/select_stream_fields.py", line 13, in <module>
    import xarray
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/__init__.py", line 1, in <module>
    from xarray import testing, tutorial
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/testing/__init__.py", line 1, in <module>
    from xarray.testing.assertions import (  # noqa: F401
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/testing/assertions.py", line 11, in <module>
    from xarray.core.coordinates import Coordinates
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/coordinates.py", line 18, in <module>
    from xarray.core.merge import merge_coordinates_without_align, merge_coords
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/merge.py", line 10, in <module>
    from xarray.core.alignment import deep_align
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/alignment.py", line 14, in <module>
    from xarray.core.common import DataWithCoords
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/common.py", line 17, in <module>
    from xarray.core.pdcompat import _convert_base_to_offset
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/pdcompat.py", line 44, in <module>
    from xarray.coding import cftime_offsets
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/coding/cftime_offsets.py", line 52, in <module>
    from xarray.coding.cftimeindex import CFTimeIndex, _parse_iso8601_with_reso
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/coding/cftimeindex.py", line 52, in <module>
    from xarray.coding.times import (
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/coding/times.py", line 14, in <module>
    from xarray.coding.variables import (
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/coding/variables.py", line 15, in <module>
    from xarray.core.variable import Variable
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/variable.py", line 19, in <module>
    from xarray.core.arithmetic import VariableArithmetic
  File "/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/arithmetic.py", line 16, in <module>
    from xarray.core.common import ImplementsArrayReduce, ImplementsDatasetReduce
ImportError: cannot import name 'ImplementsArrayReduce' from partially initialized module 'xarray.core.common' (most likely due to a circular import) (/home/beams/8IDIUSER/.conda/envs/gemviz/lib/python3.11/site-packages/xarray/core/common.py)
```

**Comment by prjemian** [comment]
```bash
(gemviz) 8idiuser@amber ~/gemviz $ gemviz --version
0.1.1.dev4+g2342915
(gemviz) 8idiuser@amber ~/gemviz $ git tag
0.0.1
0.0.2dev1
0.0.2dev2
0.0.2dev3
0.0.2rc4
0.1.0
0.1.0rc1
```

Switched to tag `0.1.0` and problem is still there.

**Comment by prjemian** [comment]
Checking installed version of *xarray*:

```bash
(gemviz) 8idiuser@amber ~/gemviz $ conda list xarr
# packages in environment at /home/beams/8IDIUSER/.conda/envs/gemviz:
#
# Name                    Version                   Build  Channel
xarray                    2023.12.0                pypi_0    pypi
```

Installing in new conda environment, includes xarray 2024.5.0.  App does not crash.  Problem is in xarray package.

**Comment by prjemian** [comment]
Updated xarray in existing environment, still no problem.  Introduce pinning requirement?
