### ISSUE TITLE
continuous integration - apply routine unit testing, packaging, publishing

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#99]
Begin regular execution of [unit tests](#86) and [documentation builds](#97) in GitHub Actions workflows.

**Comment by prjemian** [comment]
- [Run Tiled Server in a Container](https://blueskyproject.io/tiled/how-to/docker.html)
- [available images](https://github.com/bluesky/tiled/pkgs/container/tiled)

**Comment by prjemian** [comment]
Will need a catalog for routine testing.

**Comment by prjemian** [comment]
- #177
- #101

**Comment by prjemian** [comment]
Documentation workflow cannot get updated version number from git tag using `dev` suffix, such as `0.0.2dev3`. 

```
(bluesky_2023_3) prjemian@arf:~/.../BCDA-APS/gemviz$ gemviz --version
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/bluesky_2023_3/bin/gemviz", line 5, in <module>
    from gemviz.app import main
  File "/home/prjemian/Documents/projects/BCDA-APS/gemviz/gemviz/__init__.py", line 13, in <module>
    __version__ = get_version(root="..", relative_to=__file__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 146, in get_version
    maybe_version = _get_version(config)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 156, in _get_version
    version_string = format_version(
                     ^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 554, in format_version
    main_version = _call_version_scheme(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 542, in _call_version_scheme
    result = scheme(version)
             ^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 296, in guess_next_dev_version
    return version.format_next_version(guess_next_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 192, in format_next_version
    guessed = guess_next(self, *k, **kw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 244, in guess_next_version
    return _bump_dev(version) or _bump_regex(version)
           ^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bluesky_2023_3/lib/python3.11/site-packages/setuptools_scm/version.py", line 271, in _bump_dev
    raise ValueError(
ValueError: choosing custom numbers for the `.devX` distance is not supported.
 The 0.0.2.dev3 can't be bumped
Please drop the tag or create a new supported one ending in .dev0
```

Need to switch tagging pattern to `0.0.2rc4` or similar.  Will tag in the branch to test this.  Here it is:

```bash
(bluesky_2023_3) prjemian@arf:~/.../BCDA-APS/gemviz$ git tag 0.0.2rc4
(bluesky_2023_3) prjemian@arf:~/.../BCDA-APS/gemviz$ gemviz --version
0.0.2rc4
```

**Comment by prjemian** [comment]
See https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions for setup advice.
